// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc-LzTdEvJW5FYoUaqepbKGP0JTKnb5ww',
    appId: '1:44944540825:web:ab1d6b855cb4486e436408',
    messagingSenderId: '44944540825',
    projectId: 'bawari-1',
    authDomain: 'bawari-1.firebaseapp.com',
    storageBucket: 'bawari-1.appspot.com',
    measurementId: 'G-5V2S6E16B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCptCfH6FodiF9LMTw1e82LBxJdxchFZ0',
    appId: '1:44944540825:android:aa3f27bd662bd5db436408',
    messagingSenderId: '44944540825',
    projectId: 'bawari-1',
    storageBucket: 'bawari-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX5natcQJ8tNbQLJks-iVdNQZPnoBfzXU',
    appId: '1:44944540825:ios:8fab82e4fd501817436408',
    messagingSenderId: '44944540825',
    projectId: 'bawari-1',
    storageBucket: 'bawari-1.appspot.com',
    iosBundleId: 'com.example.bawari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX5natcQJ8tNbQLJks-iVdNQZPnoBfzXU',
    appId: '1:44944540825:ios:51d5f1676bb984d6436408',
    messagingSenderId: '44944540825',
    projectId: 'bawari-1',
    storageBucket: 'bawari-1.appspot.com',
    iosBundleId: 'com.example.bawari.RunnerTests',
  );
}
